name: NPM Publish and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '22'

jobs:
  build:
    name: Setup and Build
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main')
    outputs:
      version-changed: ${{ steps.check.outputs.changed }}
      new-version: ${{ steps.check.outputs.version }}
      version-type: ${{ steps.check.outputs.type }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check version changes
        uses: EndBug/version-check@v2
        id: check

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Setup Node.js
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm ci

      - name: Build project
        if: steps.check.outputs.changed == 'true'
        run: npm run build

      - name: Upload build artifacts
        if: steps.check.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/
          retention-days: 1

  publish:
    name: Publish and Release
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.version-changed == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js for publishing
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release v${{ needs.build.outputs.new-version }}
          tag: v${{ needs.build.outputs.new-version }}
          body: |
            ## 🚀 terrapi v${{ needs.build.outputs.new-version }}
            
            **Published to npm:** https://www.npmjs.com/package/terrapi
            
            ### ✨ What's New
            Check the [commit history](https://github.com/iamdantz/terrapi/commits/main) for detailed changes since the last release.
          draft: false
          prerelease: false
