name: NPM Publish and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '22'

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check version changes
        uses: EndBug/version-check@v2
        id: check
        with:
          diff-search: true

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: echo "Version change found! New version ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"

      - name: Setup Node.js
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm ci

      - name: Build project
        if: steps.check.outputs.changed == 'true'
        run: npm run build

      - name: Publish to NPM
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        if: steps.check.outputs.changed == 'true'
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release v${{ steps.check.outputs.version }}
          tag: v${{ steps.check.outputs.version }}
          body: |
            ## 🚀 terrapi v${{ steps.check.outputs.version }}
            
            **Published to npm:** https://www.npmjs.com/package/terrapi
            
            ### ✨ What's New
            Check the [commit history](https://github.com/iamdantz/terrapi/commits/main) for detailed changes since the last release.
          draft: false
          prerelease: false
